version: "3.8"
services:
  mongo:
    privileged: true
    user: root:root
    image: "mongo:${MONGODB_SERVICE_VERSION}"
    container_name: "${MONGODB_SERVICE_CONTAINER_NAME}"
    hostname: "${MONGODB_SERVICE_HOSTNAME}"
    restart: always
    ports:
     - "${MONGODB_SERVICE_PORT_27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_SERVICE_USER_NAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_SERVICE_ROOT_PASSWORD}"
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /home/mongodb/data/db:/data/db # 挂载数据目录
     - /home/mongodb/data/log:/var/log/mongodb  # 挂载日志目录
     - /home/mongodb/data/config:/etc/mongo  # 挂载配置目录
