version: "3.8"
services:
  redis:
    privileged: true
    user: root:root
    image: "redis:${REDIS_SERVICE_VERSION}"
    container_name: "${REDIS_SERVICE_CONTAINER_NAME}"
    #network_mode: "host"
    restart: unless-stopped
    ports:
      - "${REDIS_SERVICE_PORT_6379}:6379"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /home/redis/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
